"""Registry provenance: auto-generate entry markdown FROM the result JSON.

Audit #4 fix: no hand-written numbers in committed evidence. Entry text is
generated by rendering the JSON; the JSON is the single source of truth and
carries: git revision at run time + SHA-256 of every methodology module.
Any change in code hashes invalidates the binding.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REGISTRY = REPO / "registry"
METHODOLOGY_MODULES = [
    "fxedge/tick_schema.py",
    "fxedge/bars.py",
    "fxedge/sessions.py",
    "fxedge/sessions_cov.py",
    "fxedge/shard_reader.py",
    "fxedge/stream_ingest.py",
    "fxedge/registry.py",
    "fxedge/ldn_002_004_v2.py",
    "fxedge/real_run_v2.py",
    "fxedge/data_quality.py",
]


def _sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def code_hashes(repo: Path = REPO) -> dict:
    return {m: _sha256(repo / m) for m in METHODOLOGY_MODULES if (repo / m).exists()}


def bind(run_dir: Path, repo: Path = REPO) -> Path:
    """Write provenance.json into a run dir: git rev + module hashes + params."""
    rev = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True,
                         text=True, cwd=repo).stdout.strip() or "none"
    prov = {
        "git_revision": rev,
        "module_sha256": code_hashes(repo),
        "python": subprocess.run(["python3", "--version"], capture_output=True,
                                 text=True).stdout.strip(),
    }
    out = run_dir / "provenance.json"
    out.write_text(json.dumps(prov, indent=2))
    return out


def fmt_ci(ci, scale=1.0, digits=3):
    if ci is None:
        return "CI n/a"
    return f"[{ci[0] * scale:+.{digits}f}, {ci[1] * scale:+.{digits}f}]"


def render_ldn_002_004_entry(result_json: Path, out_path: Path) -> str:
    r = json.load(open(result_json))
    jb = r["joint_block_bootstrap"]
    p, ci = jb["point"], jb["ci95"]
    d = r["diagnostics"]
    st = r.get("sign_tables", {})
    s60 = st.get("ABS_signs_60", st.get("absR_signs_60", {"n_positive": 0, "n_pairs": 6}))
    s180 = st.get("ABS_signs_180", {"n_positive": 0, "n_pairs": 6})
    se = st.get("ER_signs", {"n_positive": 0, "n_pairs": 6})
    chk = r["checks"]

    lines = [
        f"# FX-LDN-002/003/004 v3 — Registry Entry (generated from {result_json.name})",
        "",
        f"- **Git revision / code hashes:** `{r['git_revision'][:12]}`; per-module SHA-256 in `(run_dir)/provenance.json`",
        f"- **Bootstrap:** {r['bootstrap']['scheme']}, B={r['bootstrap']['B']}, L={r['bootstrap']['L_days']}d, seed {r['bootstrap']['seed']}",
        f"- **Pre-declared rule:** {r['decision_rule']}",
        "",
        "| Statistic | point | 95% CI | excludes 0? |",
        "|---|---:|---:|---|",
        f"| median ER diff | {p['med_er_diff']:+.3f} | {fmt_ci(ci['med_er_diff'])} | {jb['excludes_zero']['med_er_diff']} |",
        f"| mean ER diff | {p['mean_er_diff']:+.3f} | {fmt_ci(ci['mean_er_diff'])} | {jb['excludes_zero']['mean_er_diff']} |",
        f"| P(ER>1) diff | {p['p1_diff']:+.3f} | {fmt_ci(ci['p1_diff'])} | {jb['excludes_zero']['p1_diff']} |",
        f"| P(ER>1.5) diff | {p['p15_diff']:+.3f} | {fmt_ci(ci['p15_diff'])} | {jb['excludes_zero']['p15_diff']} |",
        f"| \\|R_60\\| diff (bp) | {p['r60_diff'] * 1e4:+.2f} | {fmt_ci(ci['r60_diff'], 1e4, 2)} bp | {jb['excludes_zero']['r60_diff']} |",
        f"| \\|R_180\\| diff (bp) | {p['r180_diff'] * 1e4:+.2f} | {fmt_ci(ci['r180_diff'], 1e4, 2)} bp | {jb['excludes_zero']['r180_diff']} |",
        "",
        f"- **ER medians:** {d['er_median_comp']:.2f} vs {d['er_median_non']:.2f} (MW p={d['er_mw']['p']:.1e})",
        f"- **London-range percentile:** {d['ldn_pct_median_comp']:.2f} vs {d['ldn_pct_median_non']:.2f}",
        f"- **London relative range (bp, per-pair equal-weight):** {d['ldn_rel_range_bp_comp']:.2f} vs {d['ldn_rel_range_bp_non']:.2f}",
        f"- **Sign agreement:** |R_60| {s60['n_positive']}/{s60['n_pairs']} | |R_180| {s180['n_positive']}/{s180['n_pairs']} | ER {se['n_positive']}/{se['n_pairs']}",
        f"- **Checks:** {chk}",
        f"- **Decision:** **{r['gate_L1_decision']}**",
        "",
        "Interpretation scope: rejects the pre-registered *uplift* hypothesis only;",
        "mechanism not established; range ≠ endpoint return; exploratory on the",
        "full period (final 20% viewed). Subset-universe runs are not promotable",
        "(precondition gate enforces full universe + DATA pass + uniqueness).",
    ]
    text = "\n".join(lines) + "\n"
    out_path.write_text(text)
    return text


def render_ldn_001_entry(manifest_path: Path, result_json: Path, out_path: Path) -> str:
    import fxedge.snapshot as snap
    m = json.load(open(manifest_path))
    r = json.load(open(result_json))
    # audit #4: renderer may only mix fields from artifacts bound to ONE store
    # snapshot with identical per-pair byte counts; refuse to render otherwise.
    mf_bytes = {k: v.get("bytes", v.get("bytes_total"))
                for k, v in (m.get("store_fingerprint", {}).get("pairs", {}).items())}
    rj_bytes = r.get("store_bytes_per_pair", {})
    if mf_bytes and rj_bytes and mf_bytes != rj_bytes:
        raise RuntimeError(f"evidence disagreement: manifest bytes {mf_bytes} vs result bytes {rj_bytes} — not rendered")
    if r.get("store_snapshot_id") and m.get("store_fingerprint", {}).get("snapshot_id") not in (r["store_snapshot_id"],):
        raise RuntimeError("evidence disagreement: snapshot_id differs between manifest and result — not rendered")
    lines = [
        f"# FX-LDN-001 v3 — Registry Entry (generated from {manifest_path.name} + {result_json.name})",
        "",
        f"- **Git revision:** `{r['git_revision'][:12]}`",
        f"- **Universe complete:** {r['universe_complete']} (requested: {m['requested_pairs']})",
        f"- **Sessions per pair:** expected {m['expected_sessions']} | valid {m['unique_sessions']} "
        f"| horizon-eligible(60m) {m['horizon_eligible']}",
        f"- **Exclusions (total {r['recorded_exclusions_total']}):** {r['exclusion_reasons']}",
        f"- **Reconciliation:** valid + excluded == expected for every pair",
        f"- **Store fingerprint:** SHA-256 sample hashes in `(run_dir)/provenance.json`; "
        f"shards {m['store_fingerprint']}",
        "- **Decision:** base rates recorded; no edge claim; pre-registered exclusions held",
    ]
    text = "\n".join(lines) + "\n"
    out_path.write_text(text)
    return text